services:
  api-server:
    image: nomadics/api-forge:latest
    container_name: api-server
    ports:
      - "9999:8080"
    volumes:
      - ~/alaskartv-forge:/data/alaskartv-forge
      - ~/.ssh/:/home/appuser/.ssh
    restart: unless-stopped
    hostname: alaskar-api
